#include "../louro.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef ENV_HEADER
// Included via -DENV_HEADER='"my_env.h"'
#include ENV_HEADER
#else
#error "ENV_HEADER must be defined!"
#endif

// We calculate the count automatically from the user's louro_exports array
int global_var_count = sizeof(louro_exports) / sizeof(louro_exports[0]);

const char* get_var_c_name(const void* ptr) {
    for (int i = 0; i < global_var_count; i++) {
        if (louro_exports[i].address == ptr && TYPE_MASK(louro_exports[i].type) == LOURO_VARIABLE) {
            return louro_exports[i].name; // Emitting the variable name exactly as it was bound
        }
    }
    return "unknown_var";
}

void louro_emit_c(const LouroExpression *n) {
    if (!n) return;
    
    int type = TYPE_MASK(n->type);
    
    if (type == LOURO_CONSTANT) {
        printf("%f", n->value);
        return;
    }
    
    if (type == LOURO_VARIABLE) {
        printf("%s", get_var_c_name(n->bound));
        return;
    }
    
    int arity = ARITY(n->type);
    
    // Look up the C function name in the environment
    const char *c_func = NULL;
    for (int i = 0; i < global_var_count; i++) {
        if (louro_exports[i].address == n->function) {
            c_func = (const char*)louro_exports[i].context;
            break;
        }
    }
    
    if (!c_func) c_func = "unknown_func";

    printf("%s(", c_func);
    for (int i = 0; i < arity; i++) {
        louro_emit_c((LouroExpression*)n->parameters[i]);
        if (i < arity - 1) printf(", ");
    }
    printf(")");
}

static char *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(sz + 1);
    if (buf) {
        size_t rb = fread(buf, 1, sz, f);
        buf[rb] = '\0';
        if (out_len) *out_len = rb;
    }
    fclose(f);
    return buf;
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: template_aot <file.arara>\n");
        return 1;
    }

    size_t len = 0;
    char* input = read_file(argv[1], &len);
    if (!input) {
        fprintf(stderr, "Error reading input\n");
        return 1;
    }

    int err;
    LouroExpression *compiled = louro_compile(input, louro_exports, global_var_count, &err);
    if (!compiled) {
        fprintf(stderr, "Syntax Error: Failed to compile louro expression at %d\n", err);
        return 1;
    }
    
    printf("// --- C Code Generated by Louco AOT ---\n");
    
    // Inject the user's environment if they defined it so the generated C code has access to the custom C functions!
    #ifdef ENV_HEADER
    printf("#include \"%s\"\n", ENV_HEADER);
    #endif
    
    printf("\n// Transpiled script from: %s\n", argv[1]);
    printf("int main() {\n");
    printf("    double _result = ");
    
    louro_emit_c(compiled);
    
    printf(";\n    return 0;\n}\n");
    printf("// --------------------------------------\n");

    louro_free(compiled);
    free(input);

    return 0;
}
